// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int howManyTimes = Integer.parseInt(args[0]);
		int bigger = 0;
		int smallOrEqual = 0;
		double ratio =0;

		for (int i = 0; i < howManyTimes; i++){
			double random = Math.random();
			if (random > 0.5) {
				bigger += 1;
			}
			if (random <= 0.5) {
				smallOrEqual += 1;
			}
		}
		System.out.println("> 0.5: " + bigger + " times");
		System.out.println("<= 0.5: " + smallOrEqual + " times");

		double bigger1 = bigger + 0;
		double smallOrEqual1 = smallOrEqual + 0;
	    if ((bigger1 == 0) || (smallOrEqual1 == 0)) {
			System.out.println("");
		} else if (bigger1 < smallOrEqual1) {
			ratio = bigger1 / smallOrEqual1;
			System.out.println("Ratio: " + ratio);
		} else {
			ratio = smallOrEqual1 / bigger1;
			System.out.println("Ratio: " + ratio);
		}
	}
}
